//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36373
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListDllsParser.Dsl.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestInputResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestInputResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ListDllsParser.Dsl.Tests.TestInputResources", typeof(TestInputResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------------
        ///cmd.exe pid: 3828
        ///Command line: &quot;cmd.exe&quot; /s /k pushd &quot;D:\downloads&quot;
        ///
        ///Base                Size      Path
        ///0x000000002a830000  0x59000   C:\Windows\system32\cmd.exe
        ///	Verified:	Microsoft Windows
        ///	Publisher:	Microsoft Corporation
        ///	Description:	Обработчик команд Windows
        ///	Product:	Операционная система Microsoft® Windows®
        ///	Version:	10.0.14393.0
        ///	File version:	6.2.14393.0
        ///	Create time:	Sat Jul 16 05:23:21 2016
        ///
        ///0x00000000ae [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessInfo {
            get {
                return ResourceManager.GetString("ProcessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching processes were found.
        ///.
        /// </summary>
        internal static string ProcessInfoEmpty {
            get {
                return ResourceManager.GetString("ProcessInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ListDLLs v2.25 - DLL lister for Win9x/NT
        ///Copyright (C) 1997-2004 Mark Russinovich
        ///Sysinternals - www.sysinternals.com
        ///
        ///------------------------------------------------------------------------------
        ///cmd.exe pid: 188
        ///Command line: &quot;C:\WINDOWS\system32\cmd.exe&quot; 
        ///
        ///  Base        Size      Version	        Path
        ///  0x4ad00000  0x61000   5.01.2600.5512  C:\WINDOWS\system32\cmd.exe
        ///  0x773d0000  0x103000  6.00.2900.6028  C:\WINDOWS\WinSxS\x86_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.2600.6028 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessInfoNt5 {
            get {
                return ResourceManager.GetString("ProcessInfoNt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x000000002a830000  0x59000   C:\Windows\system32\cmd.exe
        ///	Verified:	Microsoft Windows
        ///	Publisher:	Microsoft Corporation
        ///	Description:	Обработчик команд Windows
        ///	Product:	Операционная система Microsoft® Windows®
        ///	Version:	10.0.14393.0
        ///	File version:	6.2.14393.0
        ///	Create time:	Sat Jul 16 05:23:21 2016
        ///.
        /// </summary>
        internal static string ProcessModuleInfo {
            get {
                return ResourceManager.GetString("ProcessModuleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   0x7c900000  0xb2000   5.01.2600.6055  C:\WINDOWS\system32\ntdll.dll
        ///.
        /// </summary>
        internal static string ProcessModuleInfoNt5 {
            get {
                return ResourceManager.GetString("ProcessModuleInfoNt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ListDLLs v2.25 - DLL lister for Win9x/NT
        ///Copyright (C) 1997-2004 Mark Russinovich
        ///Sysinternals - www.sysinternals.com
        ///
        ///------------------------------------------------------------------------------
        ///kashell.exe pid: 3528
        ///Command line: kashell.exe scan /ap c:\all_KASSDK_edited
        ///
        ///  Base        Size      Version	        Path
        ///  0x00400000  0x87000                   C:\KASSDK\kashell\kashell.exe
        ///  0x7c900000  0xb2000   5.01.2600.6055  C:\WINDOWS\system32\ntdll.dll
        ///  0x7c800000  0xf6000   5.01.2600.653 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RealListNt5 {
            get {
                return ResourceManager.GetString("RealListNt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------------
        ///kashell.exe pid: 3080
        ///Command line: kashell.exe  scan /ap c:\all_KASSDK_edited
        ///
        ///Base                Size      Path
        ///0x000000003f1f0000  0xf0000   C:\KASSDK_6.0.0.258_x64\kashell\kashell.exe
        ///	Verified:	Unsigned
        ///	Publisher:	n/a
        ///	Description:	n/a
        ///	Product:	n/a
        ///	Version:	n/a
        ///	File version:	n/a
        ///	Create time:	Thu Dec 22 00:34:52 2016
        ///
        ///0x0000000076d00000  0x1a9000  C:\Windows\SYSTEM32\ntdll.dll
        ///	Verified:	Microsoft Windows [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RealListNt6 {
            get {
                return ResourceManager.GetString("RealListNt6", resourceCulture);
            }
        }
    }
}
